package br.com.alura.javaEJdbcTrabalhandoComBancoDeDados;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

public class TestaConexao {
	public static void main(String[] args) throws SQLException{
		Connection connection = new ConnectionPool().getConection();
		System.out.println("Abrindo uma conexão com sucesso!");
		connection.close();
	}

}

//Rodar o servidor pelo cmd:
//cd até a pasta do projeto
//java -cp hsqldb.jar org.hsqldb.server.Server --dbname.0 loja-virtual --database.0 file:loja-virtual

//Rodar o visualizador do Banco pelo cmd
//cd até a pasta do projeto
//java -cp hsqldb.jar org.hsqldb.util.DatabaseManager

//Escolhemos o tipo: HSQL Database Engine Server
//Ajustamos a URL, ex: jdbc:hsqldb:hsql://localhost/loja-virtual -> nome do banco

//Criamos a tabela 
//CREATE TABLE Produto (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//nome VARCHAR(255), descricao VARCHAR(255))

//Iserindo dados
//insert into Produto values (1, 'Geladeira', 'Geladeira duas portas');

//adicionando coluna na tabela
//alter table *Tabela* add column *nome do campo* *tipo*
//exemplo: alter table Produto add column categoria_id integer

//Atualizando dados da tabela
//uptade Produto set categoria_id=0 where id in(1,2)

